version: "3.3"
services:
 app:
  image: punchbot_app:latest
  ports:
   - '443:443'
  build:
    context: .
  depends_on:
   - redis
  environment:
   - AUTH_URL=${AUTH_URL}
   - DISCORD_TOKEN=${DISCORD_TOKEN}
   - TWITTER_CONSUMER=${TWITTER_CONSUMER}
   - FACEBOOK_APPID=${FACEBOOK_APPID}
   - FACEBOOK_APPID_SECRET=${FACEBOOK_APPID_SECRET}
   - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
   - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
   - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
   - NOTIFICATION_CHANNELS=${NOTIFICATION_CHANNELS}
   - COMMAND_CHANNELS=${COMMAND_CHANNELS}
   - TIMER=${TIMER}
   - PUNCHSITE=${PUNCHSITE}
   - REDIS_HOST=${REDIS_HOST}
   - REDIS_PORT=${REDIS_PORT}
   - REDIS_PASSWORD=${REDIS_PASSWORD}
   - PUNCHBOT_ALLOWERDUSERS_HYPED=${PUNCHBOT_ALLOWERDUSERS_HYPED}

 redis:
  image: redis:latest
  ports:
    - '6379:6379'
  volumes:
    - redis:/data

volumes:
  redis:
